TEMPLATE = app
TARGET = thunar/thunar
CONFIG = c99 link_pkgconfig
DEFINES = _GNU_SOURCE
INCLUDEPATH =
PKGCONFIG =

PKGCONFIG += libxfce4ui-2
PKGCONFIG += gtk+-3.0
PKGCONFIG += glib-2.0

HEADERS = \
    plugins/thunar-apr/thunar-apr-abstract-page.h \
    plugins/thunar-apr/thunar-apr-desktop-page.h \
    plugins/thunar-apr/thunar-apr-image-page.h \
    plugins/thunar-apr/thunar-apr-private.h \
    plugins/thunar-apr/thunar-apr-provider.h \
    plugins/thunar-sbr/thunar-sbr-case-renamer.h \
    plugins/thunar-sbr/thunar-sbr-date-renamer.h \
    plugins/thunar-sbr/thunar-sbr-enum-types.h \
    plugins/thunar-sbr/thunar-sbr-insert-renamer.h \
    plugins/thunar-sbr/thunar-sbr-number-renamer.h \
    plugins/thunar-sbr/thunar-sbr-provider.h \
    plugins/thunar-sbr/thunar-sbr-remove-renamer.h \
    plugins/thunar-sbr/thunar-sbr-replace-renamer.h \
    plugins/thunar-uca/thunar-uca-chooser.h \
    plugins/thunar-uca/thunar-uca-context.h \
    plugins/thunar-uca/thunar-uca-editor.h \
    plugins/thunar-uca/thunar-uca-model.h \
    plugins/thunar-uca/thunar-uca-private.h \
    plugins/thunar-uca/thunar-uca-provider.h \
    plugins/thunar-wallpaper/twp-provider.h \
    thunar/thunar-abstract-dialog.h \
    thunar/thunar-abstract-icon-view.h \
    thunar/thunar-action-manager.h \
    thunar/thunar-application.h \
    thunar/thunar-browser.h \
    thunar/thunar-chooser-button.h \
    thunar/thunar-chooser-dialog.h \
    thunar/thunar-chooser-model.h \
    thunar/thunar-clipboard-manager.h \
    thunar/thunar-column-editor.h \
    thunar/thunar-column-model.h \
    thunar/thunar-compact-view.h \
    thunar/thunar-component.h \
    thunar/thunar-dbus-service.h \
    thunar/thunar-deep-count-job.h \
    thunar/thunar-details-view.h \
    thunar/thunar-device-monitor.h \
    thunar/thunar-device.h \
    thunar/thunar-dialogs.h \
    thunar/thunar-dnd.h \
    thunar/thunar-emblem-chooser.h \
    thunar/thunar-enum-types.h \
    thunar/thunar-file.h \
    thunar/thunar-folder.h \
    thunar/thunar-gdk-extensions.h \
    thunar/thunar-gio-extensions.h \
    thunar/thunar-gobject-extensions.h \
    thunar/thunar-gtk-extensions.h \
    thunar/thunar-history.h \
    thunar/thunar-ice.h \
    thunar/thunar-icon-factory.h \
    thunar/thunar-icon-renderer.h \
    thunar/thunar-icon-view.h \
    thunar/thunar-image.h \
    thunar/thunar-io-jobs-util.h \
    thunar/thunar-io-jobs.h \
    thunar/thunar-io-scan-directory.h \
    thunar/thunar-job-operation-history.h \
    thunar/thunar-job-operation.h \
    thunar/thunar-job.h \
    thunar/thunar-list-model.h \
    thunar/thunar-location-bar.h \
    thunar/thunar-location-button.h \
    thunar/thunar-location-buttons.h \
    thunar/thunar-location-entry.h \
    thunar/thunar-menu.h \
    thunar/thunar-navigator.h \
    thunar/thunar-notify.h \
    thunar/thunar-pango-extensions.h \
    thunar/thunar-path-entry.h \
    thunar/thunar-permissions-chooser.h \
    thunar/thunar-preferences-dialog.h \
    thunar/thunar-preferences.h \
    thunar/thunar-private.h \
    thunar/thunar-progress-dialog.h \
    thunar/thunar-progress-view.h \
    thunar/thunar-properties-dialog.h \
    thunar/thunar-renamer-dialog.h \
    thunar/thunar-renamer-model.h \
    thunar/thunar-renamer-pair.h \
    thunar/thunar-renamer-progress.h \
    thunar/thunar-sendto-model.h \
    thunar/thunar-session-client.h \
    thunar/thunar-shortcuts-icon-renderer.h \
    thunar/thunar-shortcuts-model.h \
    thunar/thunar-shortcuts-pane.h \
    thunar/thunar-shortcuts-view.h \
    thunar/thunar-side-pane.h \
    thunar/thunar-simple-job.h \
    thunar/thunar-size-label.h \
    thunar/thunar-standard-view-model.h \
    thunar/thunar-standard-view.h \
    thunar/thunar-statusbar.h \
    thunar/thunar-text-renderer.h \
    thunar/thunar-thumbnail-cache.h \
    thunar/thunar-thumbnailer.h \
    thunar/thunar-toolbar-editor.h \
    thunar/thunar-transfer-job.h \
    thunar/thunar-tree-model.h \
    thunar/thunar-tree-pane.h \
    thunar/thunar-tree-view-model.h \
    thunar/thunar-tree-view.h \
    thunar/thunar-user.h \
    thunar/thunar-util.h \
    thunar/thunar-view.h \
    thunar/thunar-window.h \
    thunarx/thunarx-file-info.h \
    thunarx/thunarx-menu-item.h \
    thunarx/thunarx-menu-provider.h \
    thunarx/thunarx-menu.h \
    thunarx/thunarx-preferences-provider.h \
    thunarx/thunarx-private.h \
    thunarx/thunarx-property-page-provider.h \
    thunarx/thunarx-property-page.h \
    thunarx/thunarx-provider-factory.h \
    thunarx/thunarx-provider-module.h \
    thunarx/thunarx-provider-plugin.h \
    thunarx/thunarx-renamer-provider.h \
    thunarx/thunarx-renamer.h \
    thunarx/thunarx.h \

SOURCES = \
    plugins/thunar-apr/thunar-apr-abstract-page.c \
    plugins/thunar-apr/thunar-apr-desktop-page.c \
    plugins/thunar-apr/thunar-apr-image-page.c \
    plugins/thunar-apr/thunar-apr-plugin.c \
    plugins/thunar-apr/thunar-apr-private.c \
    plugins/thunar-apr/thunar-apr-provider.c \
    plugins/thunar-sbr/thunar-sbr-case-renamer.c \
    plugins/thunar-sbr/thunar-sbr-date-renamer.c \
    plugins/thunar-sbr/thunar-sbr-enum-types.c \
    plugins/thunar-sbr/thunar-sbr-insert-renamer.c \
    plugins/thunar-sbr/thunar-sbr-number-renamer.c \
    plugins/thunar-sbr/thunar-sbr-plugin.c \
    plugins/thunar-sbr/thunar-sbr-provider.c \
    plugins/thunar-sbr/thunar-sbr-remove-renamer.c \
    plugins/thunar-sbr/thunar-sbr-replace-renamer.c \
    plugins/thunar-sendto-email/main.c \
    plugins/thunar-tpa/thunar-tpa.c \
    plugins/thunar-uca/thunar-uca-chooser.c \
    plugins/thunar-uca/thunar-uca-context.c \
    plugins/thunar-uca/thunar-uca-editor.c \
    plugins/thunar-uca/thunar-uca-model.c \
    plugins/thunar-uca/thunar-uca-plugin.c \
    plugins/thunar-uca/thunar-uca-private.c \
    plugins/thunar-uca/thunar-uca-provider.c \
    plugins/thunar-wallpaper/thunar-wallpaper-plugin.c \
    plugins/thunar-wallpaper/twp-provider.c \
    thunar/main.c \
    thunar/thunar-abstract-dialog.c \
    thunar/thunar-abstract-icon-view.c \
    thunar/thunar-action-manager.c \
    thunar/thunar-application.c \
    thunar/thunar-browser.c \
    thunar/thunar-chooser-button.c \
    thunar/thunar-chooser-dialog.c \
    thunar/thunar-chooser-model.c \
    thunar/thunar-clipboard-manager.c \
    thunar/thunar-column-editor.c \
    thunar/thunar-column-model.c \
    thunar/thunar-compact-view.c \
    thunar/thunar-component.c \
    thunar/thunar-dbus-service.c \
    thunar/thunar-deep-count-job.c \
    thunar/thunar-details-view.c \
    thunar/thunar-device-monitor.c \
    thunar/thunar-device.c \
    thunar/thunar-dialogs.c \
    thunar/thunar-dnd.c \
    thunar/thunar-emblem-chooser.c \
    thunar/thunar-enum-types.c \
    thunar/thunar-file.c \
    thunar/thunar-folder.c \
    thunar/thunar-gdk-extensions.c \
    thunar/thunar-gio-extensions.c \
    thunar/thunar-gobject-extensions.c \
    thunar/thunar-gtk-extensions.c \
    thunar/thunar-history.c \
    thunar/thunar-ice.c \
    thunar/thunar-icon-factory.c \
    thunar/thunar-icon-renderer.c \
    thunar/thunar-icon-view.c \
    thunar/thunar-image.c \
    thunar/thunar-io-jobs-util.c \
    thunar/thunar-io-jobs.c \
    thunar/thunar-io-scan-directory.c \
    thunar/thunar-job-operation-history.c \
    thunar/thunar-job-operation.c \
    thunar/thunar-job.c \
    thunar/thunar-list-model.c \
    thunar/thunar-location-bar.c \
    thunar/thunar-location-button.c \
    thunar/thunar-location-buttons.c \
    thunar/thunar-location-entry.c \
    thunar/thunar-menu.c \
    thunar/thunar-navigator.c \
    thunar/thunar-notify.c \
    thunar/thunar-pango-extensions.c \
    thunar/thunar-path-entry.c \
    thunar/thunar-permissions-chooser.c \
    thunar/thunar-preferences-dialog.c \
    thunar/thunar-preferences.c \
    thunar/thunar-progress-dialog.c \
    thunar/thunar-progress-view.c \
    thunar/thunar-properties-dialog.c \
    thunar/thunar-renamer-dialog.c \
    thunar/thunar-renamer-model.c \
    thunar/thunar-renamer-pair.c \
    thunar/thunar-renamer-progress.c \
    thunar/thunar-sendto-model.c \
    thunar/thunar-session-client.c \
    thunar/thunar-shortcuts-icon-renderer.c \
    thunar/thunar-shortcuts-model.c \
    thunar/thunar-shortcuts-pane.c \
    thunar/thunar-shortcuts-view.c \
    thunar/thunar-side-pane.c \
    thunar/thunar-simple-job.c \
    thunar/thunar-size-label.c \
    thunar/thunar-standard-view-model.c \
    thunar/thunar-standard-view.c \
    thunar/thunar-statusbar.c \
    thunar/thunar-text-renderer.c \
    thunar/thunar-thumbnail-cache.c \
    thunar/thunar-thumbnailer.c \
    thunar/thunar-toolbar-editor.c \
    thunar/thunar-transfer-job.c \
    thunar/thunar-tree-model.c \
    thunar/thunar-tree-pane.c \
    thunar/thunar-tree-view-model.c \
    thunar/thunar-tree-view.c \
    thunar/thunar-user.c \
    thunar/thunar-util.c \
    thunar/thunar-view.c \
    thunar/thunar-window.c \
    thunarx/thunarx-config.c \
    thunarx/thunarx-file-info.c \
    thunarx/thunarx-menu-item.c \
    thunarx/thunarx-menu-provider.c \
    thunarx/thunarx-menu.c \
    thunarx/thunarx-preferences-provider.c \
    thunarx/thunarx-private.c \
    thunarx/thunarx-property-page-provider.c \
    thunarx/thunarx-property-page.c \
    thunarx/thunarx-provider-factory.c \
    thunarx/thunarx-provider-module.c \
    thunarx/thunarx-provider-plugin.c \
    thunarx/thunarx-renamer-provider.c \
    thunarx/thunarx-renamer.c \

DISTFILES = \
    install.sh \
    meson.build \


