#!/bin/sh

test "x$DISPLAY" != "x" || DISPLAY=:0

dbus-send --session --print-reply --dest=org.xfce.FileManager \
  /org/xfce/FileManager \
  org.xfce.FileManager.DisplayPreferencesDialog \
  "string:$DISPLAY" "string:$DESKTOP_STARTUP_ID" 1> /dev/null
