#!/bin/sh
#
# vi:set et ai sw=2 sts=2 ts=2: */

if [ -n "$WAYLAND_DISPLAY" ]; then
  THUNAR_DISPLAY=$WAYLAND_DISPLAY
elif [ -n "$DISPLAY" ]; then
  THUNAR_DISPLAY=$DISPLAY
else
  THUNAR_DISPLAY=:0
fi

output=`dbus-send --session --print-reply --dest=org.xfce.FileManager \
  /org/xfce/FileManager org.xfce.FileManager.DisplayPreferencesDialog \
  "string:$THUNAR_DISPLAY" "string:$DESKTOP_STARTUP_ID"`

if ! [ $? -eq 0 ]; then
  echo $output
  exit 1
fi
